name: Publish

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          pyinstaller_ver: '==6.*'
          spec: 'compile.py'
          upload_exe_with_name: 'kf_compile_tool'
          options: --onefile
